-- BUILDINGS TABLE
CREATE TABLE IF NOT EXISTS BUILDINGS (
                                         BUILDING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                         NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
    );

-- ROOMS TABLE
CREATE TABLE IF NOT EXISTS ROOMS (
                                     ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                     ROOM_NAME VARCHAR(255),
    ROOM_NUMBER VARCHAR(100) NOT NULL,
    ROOM_CAPACITY INT NOT NULL,
    BUILDING_ID BIGINT NOT NULL,
    CONSTRAINT FK_ROOMS_BUILDING FOREIGN KEY (BUILDING_ID)
    REFERENCES BUILDINGS (BUILDING_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );

-- EVENTS TABLE
CREATE TABLE IF NOT EXISTS EVENTS (
                                      EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                      EVENT_NAME VARCHAR(100) NOT NULL,
    START_DATE_TIME TIMESTAMP NOT NULL, -- Replacing STARTED_AT
    END_DATE_TIME TIMESTAMP NOT NULL   -- Replacing ENDED_AT
    );

-- EVENT_ROOMS TABLE
CREATE TABLE IF NOT EXISTS EVENT_ROOMS (
                                           EVENT_ROOMS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                           EVENT_ID BIGINT NOT NULL,
                                           ROOM_ID BIGINT NOT NULL,
                                           CONSTRAINT FK_EVENT_ROOMS_EVENT FOREIGN KEY (EVENT_ID)
    REFERENCES EVENTS (EVENT_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_EVENT_ROOMS_ROOM FOREIGN KEY (ROOM_ID)
    REFERENCES ROOMS (ROOM_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );